### ISSUE TITLE
coveralls.io mapping back to file

### ISSUE THREAD

**Issue by daurnimator** [moteus/lua-travis-example#14]
In the current state, coveralls can't figure out the mapping from full path (as installed by `luarocks make`) to path in repository.

Infact, doing so would require lua-coveralls to learn about how rockspecs work.

So, instead I'm just testing from the current directory using `luarocks install --only-deps` to set things up.
See https://github.com/daurnimator/lua-http/commit/daa3d956da8ea1a3f0c2e088894e981b444cdfce

[Before](https://coveralls.io/builds/3101037/source?filename=%2Fhome%2Ftravis%2Fbuild%2Fdaurnimator%2Flua-http%2Finstall%2Fluarocks%2Fshare%2Flua%2F5.1%2Fhttp%2Fheaders.lua)
[After](https://coveralls.io/builds/3101105/source?filename=.%2Fhttp%2Fheaders.lua)

**Comment by moteus** [comment]
Try add this lines to `.luacov` config file
```Lua
  coveralls = {
    pathcorrect = {
      {"^.-/share/lua/5.%d/", "src/lua/"}
    }
  },
```
This should correct path like `/home/travis/build/moteus/lua-travis-example/install/luarocks/share/lua/5.3/foo.lua` to `src/lua/foo.lua`

**Comment by daurnimator** [comment]
Good to know.

This doesn't solve the case where in a rockspec you install a file to a different name
e.g. `["foo.init"] = "foo.lua"` 
But I guess those cases you can add an extra `pathcorrect` line.

**Comment by moteus** [comment]
I think this should be done by luacov itself (not luacov-coveralls).
It should get path to real file and I belive it does.
